config/routes.rb
Rails.application.routes.draw do
  
  get 'titles', to: 'pages#titles'

  get 'authors', to: 'pages#authors'

  get 'subjects', to: 'pages#subjects'

  get 'bios', to: 'pages#bios'

  resources :blogs

  root to: 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]

  def index
    @blogs = Blog.all
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was created.'}
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.'}
      else
        format.html {render :edit}
      end
    end
  end



  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was deleted'}
    end
  end

private

  def set_blog
        @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:author, :title)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :all_blogs, only: [:home, :titles, :authors, :subjects, :bios]
  def home
  end

  def titles
  end

  def authors
  end

  def subjects
  end

  def bios
  end

  def all_blogs
    @blogs = Blog.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_area :author, id: :blog_author %>
  
  </div><div class="field">
    <%= form.label :subject %>
    <%= form.text_area :subject, id: :blog_subject%>
  </div>

    </div><div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :blog_bio%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Edit Book Listing</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %> </p>
<h1>Best Sellers</h1>

<%= link_to 'New Blog', new_blog_path%>
<br>

<% @blogs.each do |blog| %>
  <div><%= blog.author %></div>
  <div><%= blog.title %></div>
  <div><%= blog.bio %></div>
  <div><%= image_tag blog.profile_image unless blog.profile_image.nil? %></div>
  <div><%= blog.age %></div>
  <div><%= link_to 'Show', blog %> </div>
  <div><%= link_to 'Edit', edit_blog_path(blog) %> </div>
  <div><%= link_to 'Delete', blog, method: :delete, data: { confirm: 'Are you sure?'} %> </div>
<% end %>

app/views/blogs/new.html.erb
<h1>New Best Seller</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Author</strong>
  <%= @blog.author %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthorBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/nav" %>
    <%= yield %>
  </body>
</html>

app/views/pages/authors.html.erb
<h1>Featured Authors</h1>
<div>
<% @blogs.each do |blog| %>
<ul>

<%= link_to blog.author, blog_path(blog) %>
</ul>
<% end %>
</div>

app/views/pages/bios.html.erb
<h1>Author Biographies</h1>
<div>
<% @blogs.each do |blog| %>
<ul>
  <div>
    <%= link_to blog.author, blog_path(blog) %>
    <%= blog.bio unless blog.bio.nil? %>
  <div>
</ul>
<% end %>
</div>

app/views/pages/home.html.erb
<h1>Home</h1>

<div><% @blogs.each do |blog| %>
  <div><%= blog.author %></div>
  <div><%= image_tag blog.profile_image unless blog.profile_image.nil? %></div>


<% end %>
</div>

app/views/pages/subjects.html.erb
<h1>Subjects</h1>

<div>
<% @blogs.each do |blog| %>
<ul>

<%= link_to blog.subject, blog_path(blog) unless blog.subject.nil? %>
</ul>
<% end %>
</div>

app/views/pages/titles.html.erb
<h1>Book Titles</h1>

<div>
<% @blogs.each do |blog| %>
<ul>

<%= link_to blog.title, blog_path(blog) %>
</ul>
<% end %>
</div>

app/views/shared/_nav.html.erb
<div class="'nav'">
        <div><%= link_to "Home", root_path%></div>
        <div><%= link_to "Best Sellers", blogs_path%></div>
        <div><%= link_to "Authors", authors_path%></div>
        <div><%= link_to "Bios", bios_path%></div>
        <div><%= link_to "Subjects", subjects_path%></div>
        <div><%= link_to "Titles", titles_path%></div>
    </div>